config/routes.rb
Rails.application.routes.draw do
  get 'login_modal/index'
  get 'image_gallery/index'
  get 'product_modal/index'
  get 'email_subscribes/index'
  root 'site#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/email_subscribes_controller.rb
class EmailSubscribesController < ApplicationController
  def index
  end
end

app/controllers/image_gallery_controller.rb
class ImageGalleryController < ApplicationController
  def index
  end
end

app/controllers/login_modal_controller.rb
class LoginModalController < ApplicationController
  def index
  end
end

app/controllers/product_modal_controller.rb
class ProductModalController < ApplicationController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_subscribes_helper.rb
module EmailSubscribesHelper
end

app/helpers/image_gallery_helper.rb
module ImageGalleryHelper
end

app/helpers/login_modal_helper.rb
module LoginModalHelper
end

app/helpers/product_modal_helper.rb
module ProductModalHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/email_subscribes/index.html.erb
<div class="flex items-center justify-center min-h-screen bg-zinc-700">
  <div class="bg-zinc-800 p-4 space-y-6 flex flex-col md:flex-row md:space-y-0">
   <%= image_tag "email-image.jpg", class: "h-96 rounded-lg hover:scale-105 duration-200 md:h-64 md:rounded-r-none" %>

    <div class="p-6 space-y-6 md:p-12">
      <h2 class="font-serif text-white text-lg text-center font-semibold md:text-left">
        Get diet and fitness tips in your inbox
      </h2>

      <p class="max-w-xs text-white text-xs text-center md:text-left">
        Eat better and exercise better. Sign up for the Diet&Fitness newsletter.
      </p>

      <%# Email subscribe %>
      <div class="space-y-4 flex flex-col md:flex-row md:space-y-0 md:space-x-3">
        <input
           type="text"
           class="w-full px-4 p-2 border-b border-zinc-600 bg-zinc-800 text-center"
           placeholder="Enter your email address"
        />

        <%= button_to "#", class: "w-full px-5 py-3 text-white bg-lime-500 rounded-md hover:bg-lime-700 duration-200" do %>
          Subscribe
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/image_gallery/index.html.erb
<div class="flex justify-between min-h-screen bg-cyan-50">
  <%# Card Container %>
  <div class="flex flex-col mx-auto bg-white  space-y-6 rounded-lg p-6 m-3">
    <%# Menu Container %>
    <nav class="flex flex-col items-center space-y-2 md:flex-row md:justify-end md:space-y-0 md:space-x-4">
      <div class="group">
        <%= link_to "Vector", "#" %>
        <div class="border-b-2 border-black mt-2 opacity-0 group-hover:opacity-100 duration-500"></div>
      </div>
      <div class="group">
        <%= link_to "Illustrations", "#" %>
        <div class="border-b-2 border-black mt-2 opacity-0 group-hover:opacity-100 duration-500"></div>
      </div>
      <div class="group">
        <%= link_to "Images", "#" %>
        <div class="border-b-2 border-black mt-2 opacity-0 group-hover:opacity-100 duration-500"></div>
      </div>
      <div class="group">
        <%= link_to "Icons", "#" %>
        <div class="border-b-2 border-black mt-2 opacity-0 group-hover:opacity-100 duration-500"></div>
      </div>
    </nav>

    <div class="flex flex-col space-y-4 md:flex-row md:justify-between">
      <%# Search Container %>
      <div class="flex border-b items-center">
        <input
          type="text"
          placeholder="Search"
          class="border-none ml-6"
        />
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
        </svg>
      </div>

      <%= button_to "Upload", "#", class: "w-full bg-black border border-black text-white py-4 rounded-lg
        hover:text-black hover:bg-white md:w-40" %>
    </div>

    <%# Gallery Container %>
    <div class="grid gap-3 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
      <div class="relative group">
        <%= image_tag "image1", class: "w-72" %>
        <div class="absolute flex justify-between bottom-0 left-0 right-0 p-4 text-center bg-black text-white opacity-0
          group-hover:bg-opacity-50 group-hover:opacity-100">
          <div>
            <p class="text-sm">Abstract Painting</p>
            <p class="text-sm">245 likes - 35 Shares</p>
          </div>
          <%= image_tag "bookmark.svg" %>
        </div>
      </div>
      <div class="relative group">
        <%= image_tag "image2", class: "w-72" %>
        <div class="absolute flex justify-between bottom-0 left-0 right-0 p-4 text-center bg-black text-white opacity-0
          group-hover:bg-opacity-50 group-hover:opacity-100">
          <div>
            <p class="text-sm">Abstract Painting</p>
            <p class="text-sm">245 likes - 35 Shares</p>
          </div>
          <%= image_tag "bookmark.svg" %>
        </div>
      </div>
      <div class="relative group">
        <%= image_tag "image3", class: "w-72" %>
        <div class="absolute flex justify-between bottom-0 left-0 right-0 p-4 text-center bg-black text-white opacity-0
          group-hover:bg-opacity-50 group-hover:opacity-100">
          <div>
            <p class="text-sm">Abstract Painting</p>
            <p class="text-sm">245 likes - 35 Shares</p>
          </div>
          <%= image_tag "bookmark.svg" %>
        </div>
      </div>
      <div class="relative group">
        <%= image_tag "image4", class: "w-72" %>
        <div class="absolute flex justify-between bottom-0 left-0 right-0 p-4 text-center bg-black text-white opacity-0
          group-hover:bg-opacity-50 group-hover:opacity-100">
          <div>
            <p class="text-sm">Abstract Painting</p>
            <p class="text-sm">245 likes - 35 Shares</p>
          </div>
          <%= image_tag "bookmark.svg" %>
        </div>
      </div>
      <div class="relative group">
        <%= image_tag "image5", class: "w-72" %>
        <div class="absolute flex justify-between bottom-0 left-0 right-0 p-4 text-center bg-black text-white opacity-0
          group-hover:bg-opacity-50 group-hover:opacity-100">
          <div>
            <p class="text-sm">Abstract Painting</p>
            <p class="text-sm">245 likes - 35 Shares</p>
          </div>
          <%= image_tag "bookmark.svg" %>
        </div>
      </div>
      <div class="relative group">
        <%= image_tag "image6", class: "w-72" %>
        <div class="absolute flex justify-between bottom-0 left-0 right-0 p-4 text-center bg-black text-white opacity-0
          group-hover:bg-opacity-50 group-hover:opacity-100">
          <div>
            <p class="text-sm">Abstract Painting</p>
            <p class="text-sm">245 likes - 35 Shares</p>
          </div>
          <%= image_tag "bookmark.svg" %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniProjects102</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/login_modal/index.html.erb
<div class="flex items-center justify-center min-h-screen bg-rose-50">
  <div class="flex bg-white rounded-lg">
    <div class="flex flex-col justify-center space-y-8 p-4 md:p-8">
      <h1 class="text-4xl font-mono font-bold">Log In</h1>
      <p class="max-w-sm font-light">Log in to your account to upload or download pictures, videos or music.</p>
      <input
         type="email"
         placeholder="Enter you email address"
         class="px-4 py-5 border border-gray-300 rounded-md"
      />

      <div class="flex flex-col space-y-4 md:flex-row md:justify-between md:items-center md:space-y-0">
        <%= link_to "Forgot password", "#", class: "text-sm text-light text-center text-cyan-700" %>

        <%= button_to "#", class: "w-full md:w-auto flex justify-center px-4 py-5
          text-white bg-cyan-500 space-x-2 rounded-md hover:bg-cyan-700 shadow-md hover:shadow-lg hover:-translate-y-0.5 duration-200" do %>
          <div class="text-white">Next</div>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M17.25 8.25 21 12m0 0-3.75 3.75M21 12H3" />
          </svg>
        <% end %>
      </div>

      <div class="border-b border-b-gray-300 w-full"></div>


      <%# Bottom Content %>
      <p class="text-sm font-light text-center text-gray-400">
        or log in with
      </p>

      <%# Bottom Buttons Container %>
      <div class="flex flex-col space-y-4 space-x-0 md:flex-row md:space-x-4 md:space-y-0">
        <%= link_to  "#", class: "md:w-auto flex items-center justify-center w-full p-4 space-x-4 rounded-md font-sans font-light
          hover:bg-opacity-90 shadow-sm hover:shadow-lg border hover:-translate-y-0.5 duraton-200" do %>
          <%= image_tag "facebook.png", class: "w-9" %>
          <div>Facebook</div>
        <% end %>
        <%= link_to  "#", class: "md:w-auto flex items-center justify-center w-full p-4 space-x-4 rounded-md font-sans font-light hover:bg-opacity-90 shadow-sm hover:shadow-lg border hover:-translate-y-0.5 duraton-200" do %>
          <%= image_tag "google.png", class: "w-9" %>
          <div>Google</div>
        <% end %>
      </div>

    </div>
    <%= image_tag "image.jpg", class: "w-[430px] hidden md:block" %>
  </div>
</div>

app/views/product_modal/index.html.erb
<div class="flex items-center justify-center min-h-screen bg-slate-100">
  <div class="flex flex-col justify-center p-6 space-y-6 bg-white md:flex-row md:p-16 md:space-y-0 md:space-x-4">
    <%= image_tag "headphone.png", class: "h-64 mx-auto hover:scale-105 duration-200 md:h-48" %>

    <div class="flex flex-col space-y-6">
      <div class="flex flex-col text-center space-y-4 md:text-left">
        <div>
          <div class="inline-block px-3 py-1 bg-black text-white text-sm rounded-full">
            Free Shipping
          </div>
        </div>

        <h1 class="max-w-sm text-2xl font-semibold">
          Razer Kraken Kitty Edt Gaming Headset Quartz
        </h1>

        <div class="flex flex-col space-y-2 text-center md:text-left">
          <p class="line-through">$799</p>
          <p class="text-4xl font-bold">$599</p>
          <p class="text-sm text-gray-300">This offer is valid until April 2rd or as long as stock</p>
        </div>

        <%= button_to "#", class: "w-full bg-blue-500 text-white border-b-8 border-b-blue-700 px-8 py-4 rounded-lg
        hover:bg-blue-700 hover:border-b-0 hover:border-t-8 hover:border-t-blue-700 duration-200 hover:shadow-lg" do %>
          Add to cart
        <% end %>

        <div class="flex items-center space-x-3" >
          <div class="h-3 w-3 bg-green-400 rounded-full hover:animate-ping"></div>
          <div>50+ pcs. in stock</div>
        </div>

        <div class="flex flex-col space-y-4 md:flex-row md:space-y-0 md:space-x-4">
          <%= button_to "#", class: "w-full flex items-center justify-center space-x-3 border-2 px-5 py-3 border-grey-300 rounded-lg shadow-sm
            hover:shadow-lg hover:-translate-y-0.5 duration-200" do %>
            <%= image_tag "weight.png", class: "w-8" %>
            <span>Add to cart</span>
          <% end %>
          <%= button_to "#", class: "w-full flex items-center justify-center space-x-3 border-2 px-5 py-3 border-grey-300 rounded-lg shadow-sm
            hover:shadow-lg hover:-translate-y-0.5 duration-200" do %>
            <%= image_tag "heart.png", class: "w-8" %>
            <span>Add to wishlist</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/site/index.html.erb
<div class="flex flex-col p-6 space-y-4 items-center justify-center">
  <%= link_to "Email Subscribe", email_subscribes_index_path, class: "btn w-48 text-center" %>
  <%= link_to "Product Modal", product_modal_index_path, class: "btn w-48 text-center" %>
  <%= link_to "Image Gallery", image_gallery_index_path, class: "btn w-48 text-center" %>
  <%= link_to "Login Modal", login_modal_index_path, class: "btn w-48 text-center" %>
</div>